import greenfoot.*; // (World, Actor, GreenfootImage, Greenfoot and MouseInfo)
/**
 * Die einzigen aktiven Akteure in der Roboterwelt sind die Roboter.
 * Die Welt besteht aus 16 * 10 Feldern.
 */
public class Planet extends World
{
    private static int zellenGroesse = 50;

    /**
     * Erschaffe eine Welt mit ... Zellen.
     */
    public Planet()
    {
        super(34, 18, zellenGroesse);
        setBackground("images/boden.png");
        setPaintOrder(String.class, Rover.class, Marke.class, Gestein.class, Huegel.class);
        Greenfoot.setSpeed(20); 
        prepare();
    }
    
    /**
     * Bereite die Welt für den Programmstart vor.
     * Das heißt: Erzeuge die Anfangs-Objekte und füge sie der Welt hinzu.
     */
    private void prepare()
    {
        Huegel huegel = new Huegel();
        addObject(huegel,10,7);
        Huegel huegel2 = new Huegel();
        addObject(huegel2,11,7);
        Huegel huegel3 = new Huegel();
        addObject(huegel3,12,7);
        Huegel huegel4 = new Huegel();
        addObject(huegel4,13,7);
        Huegel huegel5 = new Huegel();
        addObject(huegel5,14,7);
        Huegel huegel6 = new Huegel();
        addObject(huegel6,15,7);
        Huegel huegel7 = new Huegel();
        addObject(huegel7,16,7);
        Huegel huegel8 = new Huegel();
        addObject(huegel8,14,8);
        Huegel huegel9 = new Huegel();
        addObject(huegel9,13,8);
        Huegel huegel10 = new Huegel();
        addObject(huegel10,12,8);
        Huegel huegel11 = new Huegel();
        addObject(huegel11,11,8);
        Huegel huegel12 = new Huegel();
        addObject(huegel12,10,8);
        Huegel huegel13 = new Huegel();
        addObject(huegel13,15,9);
        Huegel huegel14 = new Huegel();
        addObject(huegel14,14,9);
        Huegel huegel15 = new Huegel();
        addObject(huegel15,14,9);
        Huegel huegel16 = new Huegel();
        addObject(huegel16,12,9);
        Huegel huegel17 = new Huegel();
        addObject(huegel17,11,9);
        Huegel huegel18 = new Huegel();
        addObject(huegel18,10,9);
        Huegel huegel19 = new Huegel();
        addObject(huegel19,13,9);
        Huegel huegel20 = new Huegel();
        addObject(huegel20,16,10);
        Huegel huegel21 = new Huegel();
        addObject(huegel21,15,10);
        Huegel huegel22 = new Huegel();
        addObject(huegel22,14,10);
        Huegel huegel23 = new Huegel();
        addObject(huegel23,13,10);
        Huegel huegel24 = new Huegel();
        addObject(huegel24,12,10);
        Huegel huegel25 = new Huegel();
        addObject(huegel25,11,10);
        removeObject(huegel18);
        Huegel huegel129 = new Huegel();
        addObject(huegel129,11,12);
        Huegel huegel26 = new Huegel();
        addObject(huegel26,12,12);
        Huegel huegel27 = new Huegel();
        addObject(huegel27,13,12);
        Huegel huegel28 = new Huegel();
        addObject(huegel28,13,11);
        Rover rover = new Rover();
        addObject(rover,11,6);
        Gestein gestein = new Gestein();
        addObject(gestein,10,9);
        Huegel huegel30 = new Huegel();
        addObject(huegel30,20,7);
        Huegel huegel31 = new Huegel();
        addObject(huegel31,20,8);
        Huegel huegel32 = new Huegel();
        addObject(huegel32,20,9);
        Huegel huegel33 = new Huegel();
        addObject(huegel33,20,10);
        Huegel huegel34 = new Huegel();
        addObject(huegel34,21,10);
        Huegel huegel35 = new Huegel();
        addObject(huegel35,22,10);
        Huegel huegel36 = new Huegel();
        addObject(huegel36,23,10);
        Huegel huegel37 = new Huegel();
        addObject(huegel37,24,10);
        Huegel huegel38 = new Huegel();
        addObject(huegel38,25,10);
        Huegel huegel39 = new Huegel();
        addObject(huegel39,26,10);
        Huegel huegel40 = new Huegel();
        addObject(huegel40,27,10);
        Huegel huegel41 = new Huegel();
        addObject(huegel41,28,10);
        Huegel huegel42 = new Huegel();
        addObject(huegel42,29,10);
        Huegel huegel43 = new Huegel();
        addObject(huegel43,30,10);
        Huegel huegel44 = new Huegel();
        addObject(huegel44,30,9);
        Huegel huegel45 = new Huegel();
        addObject(huegel45,30,8);
        Huegel huegel46 = new Huegel();
        addObject(huegel46,30,7);
        Huegel huegel47 = new Huegel();
        addObject(huegel47,30,6);
        Huegel huegel48 = new Huegel();
        addObject(huegel48,30,5);
        huegel48.setLocation(30,5);
        Huegel huegel49 = new Huegel();
        addObject(huegel49,30,5);
        Huegel huegel50 = new Huegel();
        addObject(huegel50,30,4);
        Huegel huegel51 = new Huegel();
        addObject(huegel51,30,3);
        Huegel huegel52 = new Huegel();
        addObject(huegel52,29,3);
        Huegel huegel53 = new Huegel();
        addObject(huegel53,28,3);
        Huegel huegel54 = new Huegel();
        addObject(huegel54,27,3);
        Huegel huegel55 = new Huegel();
        addObject(huegel55,26,3);
        Huegel huegel56 = new Huegel();
        addObject(huegel56,25,3);
        Huegel huegel57 = new Huegel();
        addObject(huegel57,24,3);
        Huegel huegel58 = new Huegel();
        addObject(huegel58,23,3);
        Huegel huegel59 = new Huegel();
        addObject(huegel59,22,3);
        Huegel huegel60 = new Huegel();
        addObject(huegel60,21,3);
        Huegel huegel61 = new Huegel();
        addObject(huegel61,20,3);
        Huegel huegel62 = new Huegel();
        addObject(huegel62,20,4);
        Huegel huegel63 = new Huegel();
        addObject(huegel63,20,5);
        Huegel huegel64 = new Huegel();
        addObject(huegel64,20,6);
        Huegel huegel65 = new Huegel();
        addObject(huegel65,22,9);
        Huegel huegel66 = new Huegel();
        addObject(huegel66,22,8);
        Huegel huegel67 = new Huegel();
        addObject(huegel67,22,7);
        Huegel huegel68 = new Huegel();
        addObject(huegel68,23,7);
        Huegel huegel69 = new Huegel();
        addObject(huegel69,25,7);
        Huegel huegel70 = new Huegel();
        addObject(huegel70,21,5);
        Huegel huegel71 = new Huegel();
        addObject(huegel71,22,5);
        Huegel huegel72 = new Huegel();
        addObject(huegel72,23,5);
        Huegel huegel73 = new Huegel();
        addObject(huegel73,25,4);
        Huegel huegel74 = new Huegel();
        addObject(huegel74,25,5);
        Huegel huegel75 = new Huegel();
        addObject(huegel75,24,7);
        removeObject(huegel69);
        Huegel hhuegel69 = new Huegel();
        addObject(hhuegel69,25,7);
        Huegel huegel76 = new Huegel();
        addObject(huegel76,24,8);
        Huegel huegel77 = new Huegel();
        addObject(huegel77,26,9);
        removeObject(huegel76);
        Huegel hhuegel76 = new Huegel();
        addObject(hhuegel76,24,8);
        removeObject(huegel69);
        Huegel hhhuegel69 = new Huegel();
        addObject(hhhuegel69,26,8);
        Huegel huegel78 = new Huegel();
        addObject(huegel78,26,7);
        Huegel huegel79 = new Huegel();
        addObject(huegel79,26,5);
        Huegel huegel80 = new Huegel();
        addObject(huegel80,27,5);
        Huegel huegel81 = new Huegel();
        addObject(huegel81,28,5);
        Huegel huegel82 = new Huegel();
        addObject(huegel82,28,7);
        Huegel huegel83 = new Huegel();
        addObject(huegel83,28,8);
        Huegel huegel84 = new Huegel();
        addObject(huegel84,27,7);
        Gestein gestein2 = new Gestein();
        addObject(gestein2,21,4);
        Huegel huegel88 = new Huegel();
        addObject(huegel88,0,2);
        Huegel huegel89 = new Huegel();
        addObject(huegel89,0,3);
        Huegel huegel90 = new Huegel();
        addObject(huegel90,0,4);
        Huegel huegel91 = new Huegel();
        addObject(huegel91,0,5);
        Huegel huegel92 = new Huegel();
        addObject(huegel92,0,6);
        Huegel huegel93 = new Huegel();
        addObject(huegel93,0,7);
        Huegel huegel94 = new Huegel();
        addObject(huegel94,8,7);
        Huegel huegel95 = new Huegel();
        addObject(huegel95,8,6);
        Huegel huegel96 = new Huegel();
        addObject(huegel96,8,5);
        Huegel huegel97 = new Huegel();
        addObject(huegel97,8,4);
        Huegel huegel98 = new Huegel();
        addObject(huegel98,8,3);
        Huegel huegel99 = new Huegel();
        addObject(huegel99,8,2);
        Huegel huegel100 = new Huegel();
        addObject(huegel100,3,7);
        Huegel huegel101 = new Huegel();
        addObject(huegel101,5,6);
        Huegel huegel102 = new Huegel();
        addObject(huegel102,2,5);
        Huegel huegel103 = new Huegel();
        addObject(huegel103,4,4);
        Huegel huegel104 = new Huegel();
        addObject(huegel104,5,2);
        Huegel huegel105 = new Huegel();
        addObject(huegel105,6,3);
        huegel104.setLocation(2,2);
        rover.setLocation(1,7);
    }
}